services:
  - type: web
    name: yt-vid-downloader-backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node index.js"
    envVars:
      - key: PORT
        value: 10000
